name: Deploy Release to Production

on:
  release:
    types: [published]

jobs:
  build_and_deploy:
    name: Build and Deploy Release
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://tarkovtracker.io
    steps:
      - name: Checkout Ref
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Environment
        run: npm install

      - name: Install Functions Environment
        working-directory: ./functions
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase Staging Project
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_ENVIRONMENT_CI_TOKEN }}
          PROJECT_ID: tarkovtracker-production